name: update OpenVPN
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update OpenVPN
        run: |
          set -e
          downloadLink=$(curl -sLRJ "https://openvpn.net/community-downloads/" | grep -o "https.*amd64\.msi" | head -n 1)
          mkdir -p OpenVPN/history
          cd OpenVPN/history
          curl -sLRJO "$downloadLink"
          ln -f "$(basename "$downloadLink")" "../OpenVPN-latest-amd64.msi"
          downloadLink="http://plai.de/android/$(curl -sLRJ "http://plai.de/android/" | grep -oP 'ics-openvpn-[\d.]+\.apk' | head -n 1)"
          curl -sLRJO "$downloadLink"
          ln -f "$(basename "$downloadLink")" "../openvpn-latest.apk"

      - uses: stefanzweifel/git-auto-commit-action@v4
